# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: weatherstation-readings

frameworkVersion: "3"

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  environment:
    bucket: "weather"
    org: "WeatherStation"
    token: ${ssm:/weatherstation-influxdb-token}
    url: "https://eu-central-1-1.aws.cloud2.influxdata.com"

functions:
  readings:
    handler: build/readingsHandler.readings
    events:
      - http:
          path: readings
          method: post
