# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: weatherstation-image

frameworkVersion: "3"

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:*"
        - "ssm:GetParameter"
        - "ssm:GetParameters"
        - "ssm:GetParametersByPath"
      Resource:
        - "*"
package:
  include:
    - fonts/**

custom:
  serverless-offline-ssm:
    stages:
      - local
    ssm:
      "/weatherstation-influxdb-token": "test-token"
      "/weatherstation-influxdb-url": "http://influxDb:8086/"

plugins:
  - serverless-offline-ssm
  - serverless-offline

# The `functions` block defines what code to deploy
functions:
  image:
    handler: build/imageHandler.image
    events:
      - http:
          path: image.png
          method: get
    environment:
      bucket: weather
      org: WeatherStation
      token: ${ssm:/weatherstation-influxdb-token}
      url: ${ssm:/weatherstation-influxdb-url}
